// Frontend_Development_HandsOn_08/src/components/CourseCard.vue
<script setup>
defineProps({
  id: Number,
  name: String,
  code: String,
  credits: Number,
  grade: String
});
</script>

<template>
  <article class="course-card">
    <h3><RouterLink :to="`/courses/${id}`">{{ name }}</RouterLink></h3>
    <p>{{ code }}</p>
    <span class="credits">{{ credits }} credits &middot; Grade: {{ grade }}</span>
  </article>
</template>

// Frontend_Development_HandsOn_07/src/app/components/course-card/course-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  standalone: false,
  templateUrl: './course-card.component.html',
  styleUrl: './course-card.component.css'
})
export class CourseCardComponent {
  @Input() name!: string;
  @Input() code!: string;
  @Input() credits!: number;
  @Input() grade!: string;
}

<article class="course-card" tabindex="0">
  <h3>{{ name }}</h3>
  <p>{{ code }}</p>
  <span class="credits">{{ credits }} credits &middot; Grade: {{ grade }}</span>
</article>
