// Frontend_Development_HandsOn_10/src/components/Header.jsx
import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';

export default function Header({ siteName }) {
  const enrolledCount = useSelector((state) => state.enrollment.enrolledCourses.length);

  return (
    <header>
      <div className="site-name">{siteName}</div>
      <nav aria-label="Main navigation">
        <ul>
          <li><Link to="/" className="nav-link">Home</Link></li>
          <li><Link to="/courses" className="nav-link">Courses</Link></li>
          <li>
            <Link to="/profile" className="nav-link">
              Profile <span className="badge">{enrolledCount}</span>
            </Link>
          </li>
        </ul>
      </nav>
    </header>
  );
}

// Frontend_Development_HandsOn_08/src/components/Header.vue
<script setup>
import { useEnrollmentStore } from '../stores/enrollment';
import { storeToRefs } from 'pinia';

const store = useEnrollmentStore();
const { enrolledCourses } = storeToRefs(store);
</script>

<template>
  <header>
    <div class="site-name">Student Portal</div>
    <nav aria-label="Main navigation">
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">Profile ({{ enrolledCourses.length }})</RouterLink>
    </nav>
  </header>
</template>
