// Frontend_Development_HandsOn_07/src/app/components/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  standalone: false,
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {
  siteName = 'Student Portal';
}

<header class="site-header">
  <div class="site-name">{{ siteName }}</div>
  <nav aria-label="Main navigation">
    <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact:true}">Home</a>
    <a routerLink="/profile" routerLinkActive="active">Profile</a>
  </nav>
</header>

// Frontend_Development_HandsOn_08/src/components/Header.vue
<script setup>
import { useEnrollmentStore } from '../stores/enrollment';
import { storeToRefs } from 'pinia';

const store = useEnrollmentStore();
const { enrolledCourses } = storeToRefs(store);
</script>

<template>
  <header>
    <div class="site-name">Student Portal</div>
    <nav aria-label="Main navigation">
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">Profile ({{ enrolledCourses.length }})</RouterLink>
    </nav>
  </header>
</template>
