// Frontend_Development_HandsOn_08/src/components/CourseCard.vue
<script setup>
defineProps({
  id: Number,
  name: String,
  code: String,
  credits: Number,
  grade: String
});
</script>

<template>
  <article class="course-card">
    <h3><RouterLink :to="`/courses/${id}`">{{ name }}</RouterLink></h3>
    <p>{{ code }}</p>
    <span class="credits">{{ credits }} credits &middot; Grade: {{ grade }}</span>
  </article>
</template>

// Frontend_Development_HandsOn_06/src/components/CourseCard.jsx
import { Link } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { enroll } from '../store/enrollmentSlice';

export default function CourseCard({ id, name, code, credits, grade }) {
  const dispatch = useDispatch();
  const isEnrolled = useSelector((state) =>
    state.enrollment.enrolledCourses.some((c) => c.id === id)
  );

  return (
    <article className="course-card">
      <h3>
        <Link to={`/courses/${id}`}>{name}</Link>
      </h3>
      <p>{code}</p>
      <span className="credits">{credits} credits · Grade: {grade}</span>
      <button
        type="button"
        disabled={isEnrolled}
        onClick={() => dispatch(enroll({ id, name, code, credits, grade }))}
      >
        {isEnrolled ? 'Enrolled' : 'Enroll'}
      </button>
    </article>
  );
}
